openapi: 3.0.0
info:
  title: Node Auth JWT MySQL API
  version: 1.0.0
  description: API with JWT authentication and roles (USER / ADMIN) using Node.js, Express and MySQL

servers:
  - url: http://localhost:4000/api
    description: Local server

tags:
  - name: Auth
    description: Authentication operations and profile management
  - name: Users
    description: User management operations (ADMIN)

paths:
  /auth/register:
    post:
      tags:
        - Auth
      summary: Register new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                roleName:
                  type: string
                  description: 'Optional, default is USER'
      responses:
        201:
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object

  /auth/login:
    post:
      tags:
        - Auth
      summary: Login and get tokens
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: Successful login with tokens
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object

  /auth/refresh:
    post:
      tags:
        - Auth
      summary: Refresh access token using refresh token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refreshToken:
                  type: string
      responses:
        200:
          description: Token refreshed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object

  /auth/logout:
    post:
      tags:
        - Auth
      summary: Logout
      security:
        - bearerAuth: []
      responses:
        200:
          description: Successful logout
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string

  /auth/actualizar:
    get:
      tags:
        - Auth
      summary: Get authenticated user profile
      security:
        - bearerAuth: []
      responses:
        200:
          description: Profile obtained successfully
    put:
      tags:
        - Auth
      summary: Update name and email of authenticated user
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
      responses:
        200:
          description: Profile updated successfully

  /auth/password:
    put:
      tags:
        - Auth
      summary: Change password of authenticated user
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                oldPassword:
                  type: string
                newPassword:
                  type: string
      responses:
        200:
          description: Password updated successfully

  /users:
    get:
      tags:
        - Users
      summary: List of users (ADMIN only)
      security:
        - bearerAuth: []
      responses:
        200:
          description: User list obtained successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        username:
                          type: string
                        email:
                          type: string
                        role:
                          type: object
                          properties:
                            id:
                              type: integer
                            name:
                              type: string
                        status:
                          type: string
                          enum:
                            - ACTIVE
                            - INACTIVE
                            - SUSPENDED
                            - BLOCKED

  /users/{id}:
    get:
      tags:
        - Users
      summary: Get user by ID
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: User found
        404:
          description: User not found

  /users/username/{username}:
    get:
      tags:
        - Users
      summary: Get user by username (ADMIN only)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: username
          required: true
          schema:
            type: string
      responses:
        200:
          description: User found
        404:
          description: User not found

  /users/email/{email}:
    get:
      tags:
        - Users
      summary: Get user by email (ADMIN only)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: email
          required: true
          schema:
            type: string
      responses:
        200:
          description: User found
        404:
          description: User not found

  /users/{id}/activate:
    put:
      tags:
        - Users
      summary: Activate user (ADMIN only)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: User activated successfully

  /users/{id}/deactivate:
    put:
      tags:
        - Users
      summary: Deactivate user (ADMIN only)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: User deactivated successfully

  /users/{id}/suspend:
    put:
      tags:
        - Users
      summary: Suspend user (ADMIN only)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: User suspended successfully

  /users/{id}/block:
    put:
      tags:
        - Users
      summary: Block user (ADMIN only)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: User blocked successfully

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
